@echo off
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
call .venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Seeding database...
python -m app.seed
echo Starting FastAPI server...
python -m uvicorn app.main:app --reload@echo off
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
call .venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Seeding database...
python -m app.seed
echo Starting FastAPI server...
python -m uvicorn app.main:app --reload